/* eslint-disable */
// This file was generated by [specta](https://github.com/oscartbeaumont/specta). Do not edit this file manually.

export type StyleIntent = { base_archetype: string | null; class: CitationClass | null; author_format: NameFormat | null; has_bibliography: boolean | null };

export type CitationClass = "InText" | "Note" | "Numeric";

export type NameFormat = "Long" | "Short" | "EtAl";

export type DecisionPackage = { missing_fields: string[]; question: Question | null; previews: Preview[] };

export type Question = { id: string; text: string; description: string | null };

export type Preview = { label: string; html: string; choice_value: any };
